# Generated by Django 5.1.6 on 2025-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "makale_basligi",
                    models.CharField(max_length=255, verbose_name="Makale Başlığı"),
                ),
                (
                    "makale_ozeti",
                    models.TextField(
                        blank=True, null=True, verbose_name="Makale Özeti"
                    ),
                ),
                (
                    "makale_metni",
                    models.TextField(
                        blank=True, null=True, verbose_name="Makale Metni"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JudicialDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "karar_turu",
                    models.CharField(max_length=255, verbose_name="Karar Türü"),
                ),
                (
                    "karar_veren_mahkeme",
                    models.CharField(
                        max_length=255, verbose_name="Kararı Veren Mahkeme"
                    ),
                ),
                (
                    "esas_numarasi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Esas Numarası",
                    ),
                ),
                (
                    "karar_numarasi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Karar Numarası",
                    ),
                ),
                (
                    "karar_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Karar Tarihi"
                    ),
                ),
                (
                    "anahtar_kelimeler",
                    models.TextField(
                        blank=True, null=True, verbose_name="Anahtar Kelimeler"
                    ),
                ),
                (
                    "karar_ozeti",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kararın Özeti"
                    ),
                ),
                (
                    "karar_tam_metni",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kararın Tam Metni"
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="decisions/",
                        verbose_name="Dosya",
                    ),
                ),
            ],
        ),
    ]
