# Generated by Django 5.1.6 on 2025-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mevzuat_turu",
                    models.CharField(
                        choices=[
                            ("kanun", "Kanun"),
                            ("tuzuk", "Tüzük"),
                            ("yonetmelik", "Yönetmelik"),
                            ("genelge", "Genelge"),
                            ("teblig", "Tebliğ"),
                        ],
                        max_length=50,
                        verbose_name="Mevzuat Türü",
                    ),
                ),
                ("baslik", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "mevzuat_numarasi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mevzuat Numarası",
                    ),
                ),
                (
                    "yayin_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "yurutulme_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yürürlük Tarihi"
                    ),
                ),
                (
                    "resmigazete_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resmi Gazete Tarihi"
                    ),
                ),
                (
                    "konu",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Konu"
                    ),
                ),
                ("ozet", models.TextField(blank=True, null=True, verbose_name="Özet")),
                (
                    "tam_metin",
                    models.TextField(blank=True, null=True, verbose_name="Tam Metin"),
                ),
                (
                    "dosya",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legislation/",
                        verbose_name="Dosya",
                    ),
                ),
            ],
        ),
    ]
