# Generated by Django 5.1.6 on 2025-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_legislation"),
    ]

    operations = [
        migrations.AddField(
            model_name="legislation",
            name="tam_metin_html",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tam Metin (HTML)"
            ),
        ),
    ]
