# Generated by Django 5.1.6 on 2025-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_legislation_tam_metin_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="dergi",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Yayınlandığı Dergi"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="dosya",
            field=models.FileField(
                blank=True, null=True, upload_to="articles/", verbose_name="Dosya"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="yazarlar",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Yazarlar"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="makale_basligi",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Makale Başlığı"
            ),
        ),
    ]
