# Generated by Django 5.1.6 on 2025-02-17 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_article_dergi_article_dosya_article_yazarlar_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("monthly", "Aylık"),
                            ("quarterly", "Üç Aylık"),
                            ("half_yearly", "Altı Aylık"),
                            ("yearly", "Yıllık"),
                        ],
                        max_length=20,
                        verbose_name="Abonelik Planı",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Başlangıç Tarihi",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "accepted_terms",
                    models.BooleanField(
                        default=False, verbose_name="Abonelik Sözleşmesi Kabul Edildi"
                    ),
                ),
                (
                    "accepted_sale",
                    models.BooleanField(
                        default=False,
                        verbose_name="Mesafeli Satış Sözleşmesi Kabul Edildi",
                    ),
                ),
                (
                    "accepted_delivery",
                    models.BooleanField(
                        default=False,
                        verbose_name="Teslimat ve İade Şartları Kabul Edildi",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
