# Generated by Django 5.1.6 on 2025-02-18 08:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tc_or_vergi_no",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        10,
                        "T.C. Kimlik veya Vergi Numarası en az 10 karakter olmalıdır.",
                    ),
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Sadece rakam giriniz."
                    ),
                ],
                verbose_name="T.C. Kimlik / Vergi Numarası",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="accepted_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Teslimat & İade Şartları"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="accepted_sale",
            field=models.BooleanField(
                default=False, verbose_name="Mesafeli Satış Sözleşmesi"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="accepted_terms",
            field=models.BooleanField(
                default=False, verbose_name="Kullanıcı Sözleşmesi"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("monthly", "Aylık"),
                    ("quarterly", "3 Aylık"),
                    ("semi_annually", "6 Aylık"),
                    ("yearly", "Yıllık"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
