# Generated by Django 5.1.6 on 2025-07-01 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_subscription_address_subscription_tc_or_vergi_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MevzuatTuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kod",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tür Kodu"
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Tür Adı")),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("kanun", "Kanunlar"),
                            (
                                "cumhurbaskanligi_kararnamesi",
                                "Cumhurbaşkanlığı Kararnameleri",
                            ),
                            ("bakanlar_kurulu_karari", "Bakanlar Kurulu Kararları"),
                            ("cumhurbaskani_karari", "Cumhurbaşkanı Kararları"),
                            ("yonetmelik", "Yönetmelikler"),
                            ("tuzuk", "Tüzükler"),
                            ("teblig", "Tebliğler"),
                            ("genelge", "Genelgeler"),
                            ("mülga", "Mülga Mevzuat"),
                            ("uluslararasi_andlasma", "Uluslararası Andlaşmalar"),
                        ],
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("sira", models.IntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Mevzuat Türü",
                "verbose_name_plural": "Mevzuat Türleri",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="MevzuatKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "kod",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kategori Kodu"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "ust_kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.mevzuatkategori",
                        verbose_name="Üst Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mevzuat Kategorisi",
                "verbose_name_plural": "Mevzuat Kategorileri",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="MevzuatGelismis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=500, verbose_name="Başlık")),
                (
                    "mevzuat_numarasi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mevzuat Numarası",
                    ),
                ),
                (
                    "sira_numarasi",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Sıra Numarası",
                    ),
                ),
                (
                    "yayin_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                (
                    "yurutulme_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yürürlük Tarihi"
                    ),
                ),
                (
                    "yurutulme_bitis_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yürürlük Bitiş Tarihi"
                    ),
                ),
                (
                    "resmi_gazete_tarihi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Resmi Gazete Tarihi"
                    ),
                ),
                (
                    "resmi_gazete_sayisi",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Resmi Gazete Sayısı",
                    ),
                ),
                (
                    "mukerrer_sayisi",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Mükerrer Sayısı",
                    ),
                ),
                ("konu", models.TextField(blank=True, null=True, verbose_name="Konu")),
                ("ozet", models.TextField(blank=True, null=True, verbose_name="Özet")),
                (
                    "anahtar_kelimeler",
                    models.TextField(
                        blank=True, null=True, verbose_name="Anahtar Kelimeler"
                    ),
                ),
                (
                    "tam_metin",
                    models.TextField(blank=True, null=True, verbose_name="Tam Metin"),
                ),
                (
                    "tam_metin_html",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tam Metin (HTML)"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("yurutulme", "Yürürlükte"),
                            ("ilga", "İlga Edildi"),
                            ("degisiklik", "Değişiklik Yapıldı"),
                            ("mulga", "Mülga"),
                            ("geçici", "Geçici"),
                        ],
                        default="yurutulme",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "dosya",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="mevzuat_gelismis/",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "son_kontrol_tarihi",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kontrol Tarihi"
                    ),
                ),
                (
                    "kaynak_url",
                    models.URLField(blank=True, null=True, verbose_name="Kaynak URL"),
                ),
                (
                    "mevzuat_gov_tr_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Mevzuat.gov.tr ID",
                    ),
                ),
                (
                    "ilgili_mevzuatlar",
                    models.ManyToManyField(
                        blank=True,
                        to="core.mevzuatgelismis",
                        verbose_name="İlgili Mevzuatlar",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mevzuatkategori",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "mevzuat_turu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.mevzuatturu",
                        verbose_name="Mevzuat Türü",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gelişmiş Mevzuat",
                "verbose_name_plural": "Gelişmiş Mevzuatlar",
                "ordering": ["-yayin_tarihi", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MevzuatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "islem_turu",
                    models.CharField(
                        choices=[
                            ("ekleme", "Ekleme"),
                            ("guncelleme", "Güncelleme"),
                            ("silme", "Silme"),
                            ("scraping", "Veri Çekme"),
                            ("hata", "Hata"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Türü",
                    ),
                ),
                ("aciklama", models.TextField(verbose_name="Açıklama")),
                (
                    "ip_adresi",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "detaylar",
                    models.JSONField(blank=True, null=True, verbose_name="Detaylar"),
                ),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "mevzuat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.mevzuatgelismis",
                        verbose_name="İlgili Mevzuat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mevzuat Log",
                "verbose_name_plural": "Mevzuat Logları",
                "ordering": ["-kayit_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="MevzuatMadde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("madde_no", models.CharField(max_length=20, verbose_name="Madde No")),
                (
                    "madde_basligi",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Madde Başlığı",
                    ),
                ),
                (
                    "bent_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Bent No"
                    ),
                ),
                (
                    "fıkra_no",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Fıkra No"
                    ),
                ),
                ("metin", models.TextField(verbose_name="Madde Metni")),
                (
                    "metin_html",
                    models.TextField(
                        blank=True, null=True, verbose_name="Madde Metni (HTML)"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("sira", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "mevzuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maddeler",
                        to="core.mevzuatgelismis",
                        verbose_name="Mevzuat",
                    ),
                ),
                (
                    "ust_madde",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.mevzuatmadde",
                        verbose_name="Üst Madde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mevzuat Maddesi",
                "verbose_name_plural": "Mevzuat Maddeleri",
                "ordering": ["sira", "madde_no"],
                "unique_together": {("mevzuat", "madde_no", "bent_no", "fıkra_no")},
            },
        ),
        migrations.CreateModel(
            name="MevzuatDegisiklik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degisiklik_turu",
                    models.CharField(
                        choices=[
                            ("ekleme", "Madde Ekleme"),
                            ("silme", "Madde Silme"),
                            ("degistirme", "Madde Değiştirme"),
                            ("yeniden_duzenleme", "Yeniden Düzenleme"),
                            ("ilga", "İlga"),
                        ],
                        max_length=20,
                        verbose_name="Değişiklik Türü",
                    ),
                ),
                ("aciklama", models.TextField(verbose_name="Açıklama")),
                (
                    "degisiklik_tarihi",
                    models.DateField(verbose_name="Değişiklik Tarihi"),
                ),
                ("yurutulme_tarihi", models.DateField(verbose_name="Yürürlük Tarihi")),
                (
                    "kayit_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "degistiren_mevzuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degistirdikleri",
                        to="core.mevzuatgelismis",
                        verbose_name="Değiştiren Mevzuat",
                    ),
                ),
                (
                    "mevzuat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degisiklikler",
                        to="core.mevzuatgelismis",
                        verbose_name="Mevzuat",
                    ),
                ),
                (
                    "etkilenen_maddeler",
                    models.ManyToManyField(
                        blank=True,
                        to="core.mevzuatmadde",
                        verbose_name="Etkilenen Maddeler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mevzuat Değişikliği",
                "verbose_name_plural": "Mevzuat Değişiklikleri",
                "ordering": ["-degisiklik_tarihi"],
            },
        ),
        migrations.AddIndex(
            model_name="mevzuatgelismis",
            index=models.Index(
                fields=["mevzuat_turu", "durum"], name="core_mevzua_mevzuat_8422b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mevzuatgelismis",
            index=models.Index(
                fields=["yayin_tarihi"], name="core_mevzua_yayin_t_91065b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mevzuatgelismis",
            index=models.Index(
                fields=["resmi_gazete_tarihi"], name="core_mevzua_resmi_g_a4d930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mevzuatgelismis",
            index=models.Index(
                fields=["mevzuat_gov_tr_id"], name="core_mevzua_mevzuat_a1b481_idx"
            ),
        ),
    ]
