# Generated by Django 5.2.4 on 2025-07-18 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_mevzuatturu_mevzuatkategori_mevzuatgelismis_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package", models.CharField(max_length=20, verbose_name="Paket")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Sipariş No"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="İşlem No"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("success", "Başarılı"),
                            ("failed", "Başarısız"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="param_pos", max_length=50, verbose_name="Ödeme Yöntemi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "param_hash",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Param Hash"
                    ),
                ),
                (
                    "param_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Param Yanıtı"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme",
                "verbose_name_plural": "Ödemeler",
                "ordering": ["-created_at"],
            },
        ),
    ]
