# Generated by Django 5.2.4 on 2025-07-21 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Telefon numaranızı giriniz",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[\\+\\d\\s\\-\\(\\)]+$",
                                "Geçerli bir telefon numarası giriniz. (Örn: 05551234567 veya +90 555 123 45 67)",
                            )
                        ],
                        verbose_name="Telefon Numarası",
                    ),
                ),
                (
                    "is_free_trial",
                    models.BooleanField(default=True, verbose_name="Ücretsiz Deneme"),
                ),
                (
                    "free_trial_start",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ücretsiz Deneme Başlangıç"
                    ),
                ),
                (
                    "free_trial_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ücretsiz Deneme Bitiş"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Profili",
                "verbose_name_plural": "Kullanıcı Profilleri",
            },
        ),
    ]
