# Generated by Django 5.2.4 on 2025-07-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Paket Satın Alma"),
                            ("expiry_warning", "Süre Dolma Uyarısı"),
                            ("expiry", "Süre Doldu"),
                            ("free_trial_warning", "Ücretsiz Deneme Bitiyor"),
                            ("free_trial_expired", "Ücretsiz Deneme Bitti"),
                            ("system", "Sistem Bildirimi"),
                        ],
                        max_length=20,
                        verbose_name="Bildirim Türü",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                (
                    "is_sent_email",
                    models.BooleanField(
                        default=False, verbose_name="E-posta Gönderildi"
                    ),
                ),
                (
                    "is_admin_notification",
                    models.BooleanField(default=False, verbose_name="Admin Bildirimi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Okunma Tarihi"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, null=True, verbose_name="Ek Veriler"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.payment",
                        verbose_name="İlgili Ödeme",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.subscription",
                        verbose_name="İlgili Abonelik",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="core_notifi_user_id_cb8f07_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="core_notifi_notific_cbfe88_idx",
                    ),
                    models.Index(
                        fields=["is_admin_notification"],
                        name="core_notifi_is_admi_b51bd8_idx",
                    ),
                ],
            },
        ),
    ]
