# Generated by Django 5.1.6 on 2025-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='judicialdecision',
            name='detected_legal_area',
            field=models.CharField(blank=True, help_text='Otomatik tespit edilen hukuk alani', max_length=100, null=True),
        ),
    ]
