# Generated by Django 5.1.6 on 2025-09-02 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_legal_area_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tür Adı')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Tür Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('hierarchy_level', models.IntegerField(default=1, verbose_name='Hiyerarşi Seviyesi')),
                ('display_order', models.IntegerField(default=0, verbose_name='Gösterim Sırası')),
                ('color_code', models.CharField(default='#007bff', max_length=7, verbose_name='Renk Kodu')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon Sınıfı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Mevzuat Türü',
                'verbose_name_plural': 'Mevzuat Türleri',
                'ordering': ['hierarchy_level', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegislationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kategori Kodu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Dostu Ad')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='İkon')),
                ('color_code', models.CharField(default='#28a745', max_length=7, verbose_name='Renk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('display_order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.legislationcategory', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Mevzuat Kategorisi',
                'verbose_name_plural': 'Mevzuat Kategorileri',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='Başlık')),
                ('short_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kısa Başlık')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mevzuat Numarası')),
                ('sequence', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sıra Numarası')),
                ('official_gazette_date', models.DateField(blank=True, null=True, verbose_name='Resmi Gazete Tarihi')),
                ('official_gazette_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Resmi Gazete Sayısı')),
                ('duplicate_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mükerrer Sayısı')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Yayın Tarihi')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Yürürlük Tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yürürlük Bitiş Tarihi')),
                ('acceptance_date', models.DateField(blank=True, null=True, verbose_name='Kabul Tarihi')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Konu')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Özet')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Anahtar Kelimeler')),
                ('status', models.CharField(choices=[('active', 'Yürürlükte'), ('repealed', 'Yürürlükten Kaldırıldı'), ('amended', 'Değiştirildi'), ('superseded', 'Yerine Başkası Geldi'), ('suspended', 'Askıya Alındı'), ('draft', 'Taslak')], default='active', max_length=20, verbose_name='Durum')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Kaynak URL')),
                ('mevzuat_gov_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mevzuat.gov.tr ID')),
                ('pdf_url', models.URLField(blank=True, null=True, verbose_name='PDF URL')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Tam Metin')),
                ('full_text_html', models.TextField(blank=True, null=True, verbose_name='HTML Metin')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL')),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta Açıklama')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='Arama Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Son Kontrol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulandı')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Doğrulama Tarihi')),
                ('data_quality_score', models.FloatField(default=0.0, verbose_name='Veri Kalite Skoru')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.legislationcategory', verbose_name='Kategori')),
                ('legislation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.legislationtype', verbose_name='Mevzuat Türü')),
                ('related_legislations', models.ManyToManyField(blank=True, related_name='referenced_by', to='core.professionallegislation', verbose_name='İlgili Mevzuatlar')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.professionallegislation', verbose_name='Yerine Geçen')),
            ],
            options={
                'verbose_name': 'Profesyonel Mevzuat',
                'verbose_name_plural': 'Profesyonel Mevzuatlar',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegislationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50, verbose_name='Madde Numarası')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Madde Başlığı')),
                ('text', models.TextField(verbose_name='Madde Metni')),
                ('text_html', models.TextField(blank=True, null=True, verbose_name='HTML Metin')),
                ('footnotes', models.TextField(blank=True, null=True, verbose_name='Dipnotlar')),
                ('legal_notes', models.TextField(blank=True, null=True, verbose_name='Hukuki Notlar')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_repealed', models.BooleanField(default=False, verbose_name='Yürürlükten Kaldırıldı')),
                ('repeal_date', models.DateField(blank=True, null=True, verbose_name='Kaldırılma Tarihi')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.professionallegislation', verbose_name='Mevzuat')),
            ],
            options={
                'verbose_name': 'Madde',
                'verbose_name_plural': 'Maddeler',
                'ordering': ['order', 'article_number'],
            },
        ),
        migrations.CreateModel(
            name='CourtDecisionLegislationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('application', 'Uygulama'), ('interpretation', 'Yorum'), ('precedent', 'İçtihat'), ('contradiction', 'Çelişki'), ('reference', 'Atıf')], max_length=20, verbose_name='İlişki Türü')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Güven Skoru')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Doğrulandı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('court_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.judicialdecision', verbose_name='Yargıtay Kararı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.legislationarticle', verbose_name='İlgili Madde')),
                ('legislation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professionallegislation', verbose_name='Mevzuat')),
            ],
            options={
                'verbose_name': 'Karar-Mevzuat İlişkisi',
                'verbose_name_plural': 'Karar-Mevzuat İlişkileri',
            },
        ),
        migrations.AddIndex(
            model_name='professionallegislation',
            index=models.Index(fields=['legislation_type', 'status'], name='core_profes_legisla_15c263_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallegislation',
            index=models.Index(fields=['publication_date'], name='core_profes_publica_6210b5_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallegislation',
            index=models.Index(fields=['official_gazette_date'], name='core_profes_officia_e49922_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallegislation',
            index=models.Index(fields=['mevzuat_gov_id'], name='core_profes_mevzuat_e625f8_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallegislation',
            index=models.Index(fields=['slug'], name='core_profes_slug_b292ec_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallegislation',
            index=models.Index(fields=['status'], name='core_profes_status_392e53_idx'),
        ),
        migrations.AddIndex(
            model_name='legislationarticle',
            index=models.Index(fields=['legislation', 'is_active'], name='core_legisl_legisla_2883cf_idx'),
        ),
        migrations.AddIndex(
            model_name='legislationarticle',
            index=models.Index(fields=['article_number'], name='core_legisl_article_bd0980_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legislationarticle',
            unique_together={('legislation', 'article_number')},
        ),
        migrations.AlterUniqueTogether(
            name='courtdecisionlegislationrelation',
            unique_together={('court_decision', 'legislation', 'article')},
        ),
    ]
