# Generated by Django 5.1.6 on 2025-12-08 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_legislationtype_legislationcategory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legislationarticle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='legislationarticle',
            name='legislation',
        ),
        migrations.RemoveField(
            model_name='legislationcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='professionallegislation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='professionallegislation',
            name='legislation_type',
        ),
        migrations.RemoveField(
            model_name='professionallegislation',
            name='related_legislations',
        ),
        migrations.RemoveField(
            model_name='professionallegislation',
            name='superseded_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_1',
            field=models.CharField(blank=True, help_text='Mahalle, cadde, sokak ve kapı numarası', max_length=255, null=True, verbose_name='Adres Satırı 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Apartman, daire numarası gibi ek adres bilgileri (opsiyonel)', max_length=255, null=True, verbose_name='Adres Satırı 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Geçerli bir posta kodu giriniz. (Örn: 34000)')], verbose_name='Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='judicialdecision',
            name='detected_legal_area',
            field=models.CharField(blank=True, help_text='Otomatik tespit edilen hukuk alanı', max_length=50, null=True, verbose_name='Tespit Edilen Hukuk Alanı'),
        ),
        migrations.DeleteModel(
            name='CourtDecisionLegislationRelation',
        ),
        migrations.DeleteModel(
            name='LegislationArticle',
        ),
        migrations.DeleteModel(
            name='LegislationCategory',
        ),
        migrations.DeleteModel(
            name='LegislationType',
        ),
        migrations.DeleteModel(
            name='ProfessionalLegislation',
        ),
    ]
