# Generated by Django 5.1.6 on 2025-12-09 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_legislationarticle_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGazetteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Baslik')),
                ('content_type', models.CharField(choices=[('yurutme_idare', 'Yurutme ve Idare'), ('anayasa_mahkemesi', 'Anayasa Mahkemesi'), ('yargitay', 'Yargitay'), ('danistay', 'Danistay'), ('ilan', 'Ilan'), ('duyuru', 'Duyuru'), ('other', 'Diger')], max_length=50, verbose_name='Icerik Turu')),
                ('category', models.CharField(choices=[('atama_karari', 'Atama Karari'), ('yonetmelik', 'Yonetmelik'), ('teblig', 'Teblig'), ('genelge', 'Genelge'), ('cumhurbaskani_karari', 'Cumhurbaskani Karari'), ('bakanlar_kurulu_karari', 'Bakanlar Kurulu Karari'), ('kurul_karari', 'Kurul Karari'), ('mahkeme_karari', 'Mahkeme Karari'), ('ilan', 'Ilan'), ('other', 'Diger')], max_length=50, verbose_name='Kategori')),
                ('gazette_date', models.DateField(verbose_name='Resmi Gazete Tarihi')),
                ('gazette_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Resmi Gazete Sayisi')),
                ('original_url', models.URLField(max_length=500, verbose_name='Orijinal Link')),
                ('summary', models.TextField(help_text='Email de gosterilecek kisa aciklama', verbose_name='Ozet')),
                ('full_content', models.TextField(blank=True, null=True, verbose_name='Tam Icerik')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='AI Analizi')),
                ('affected_sectors', models.JSONField(blank=True, null=True, verbose_name='Etkilenen Sektorler')),
                ('importance_score', models.IntegerField(default=5, help_text='1-10 arasi', verbose_name='Onem Skoru')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('scraping_source', models.CharField(default='resmigazete.gov.tr', max_length=100, verbose_name='Kaynak')),
                ('is_included_in_email', models.BooleanField(default=True, verbose_name='Email e Dahil')),
                ('email_priority', models.IntegerField(default=5, help_text='1=En Onemli, 10=Az Onemli', verbose_name='Email Onceligi')),
            ],
            options={
                'verbose_name': 'Gunluk Gazete Icerigi',
                'verbose_name_plural': 'Gunluk Gazete Icerikleri',
                'ordering': ['-gazette_date', '-importance_score', 'email_priority'],
                'indexes': [models.Index(fields=['gazette_date', 'is_active'], name='core_dailyg_gazette_6a00b5_idx'), models.Index(fields=['content_type', 'category'], name='core_dailyg_content_7e0728_idx'), models.Index(fields=['is_included_in_email'], name='core_dailyg_is_incl_976b2a_idx')],
                'unique_together': {('title', 'gazette_date')},
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('frequency', models.CharField(choices=[('daily', 'Gunluk'), ('weekly', 'Haftalik'), ('disabled', 'Kapali')], default='daily', max_length=10, verbose_name='Siklik')),
                ('send_time', models.TimeField(default='08:00', help_text='Gunluk email gonderim saati', verbose_name='Gonderim Saati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
                ('last_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='Son Email Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gazette_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Aboneligi',
                'verbose_name_plural': 'Email Abonelikleri',
            },
        ),
        migrations.CreateModel(
            name='DailyEmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_date', models.DateField(verbose_name='Email Tarihi')),
                ('gazette_date', models.DateField(verbose_name='Resmi Gazete Tarihi')),
                ('subject', models.CharField(max_length=200, verbose_name='Baslik')),
                ('content_count', models.IntegerField(default=0, verbose_name='Icerik Sayisi')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gonderilme Tarihi')),
                ('status', models.CharField(choices=[('sent', 'Gonderildi'), ('failed', 'Basarisiz'), ('pending', 'Beklemede')], default='sent', max_length=10, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesaji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gazette_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gonderilen Email',
                'verbose_name_plural': 'Gonderilen Email ler',
                'ordering': ['-email_date', '-sent_at'],
                'unique_together': {('user', 'email_date')},
            },
        ),
    ]
