# Generated by Django 5.1.6 on 2025-12-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_daily_gazette_email_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygazettecontent',
            name='category',
            field=models.CharField(choices=[('atama_karari', 'Atama Kararı'), ('yonetmelik', 'Yönetmelik'), ('teblig', 'Tebliğ'), ('genelge', 'Genelge'), ('cumhurbaskani_karari', 'Cumhurbaşkanı Kararı'), ('bakanlar_kurulu_karari', 'Bakanlar Kurulu Kararı'), ('kurul_karari', 'Kurul Kararı'), ('mahkeme_karari', 'Mahkeme Kararı'), ('ilan', 'İlan'), ('other', 'Diğer')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='dailygazettecontent',
            name='content_type',
            field=models.CharField(choices=[('yurutme_idare', 'Yurutme ve Idare'), ('anayasa_mahkemesi', 'Anayasa Mahkemesi'), ('yargitay', 'Yargitay'), ('danistay', 'Danistay'), ('ilan', 'İlan'), ('duyuru', 'Duyuru'), ('other', 'Diğer')], max_length=50, verbose_name='Icerik Turu'),
        ),
    ]
