# Generated by Django 5.1.6 on 2025-12-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSearchLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('user_agent_hash', models.CharField(max_length=64, verbose_name='User Agent Hash')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='Arama Sayısı')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('last_search', models.DateTimeField(auto_now=True, verbose_name='Son Arama')),
            ],
            options={
                'verbose_name': 'Misafir Arama Limiti',
                'verbose_name_plural': 'Misafir Arama Limitleri',
                'unique_together': {('ip_address', 'user_agent_hash', 'date_created')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyemailsent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyemailsent',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyGazetteContent',
        ),
        migrations.RemoveField(
            model_name='emailsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyEmailSent',
        ),
        migrations.DeleteModel(
            name='EmailSubscription',
        ),
    ]
